speed up compilation

diff --git a/release/release-psp b/release/release-psp
--- a/release/release-psp
+++ b/release/release-psp
@@ -67,8 +67,8 @@ else
 fi
 
 ls -lh EBOOT.PBP
-echo X. Compress
-psp-packer EBOOT.PBP && echo "OK" || echo "Error"
+#echo X. Compress
+#psp-packer EBOOT.PBP && echo "OK" || echo "Error"
 
 EOF
 
